### ISSUE TITLE
Add a readme that tells you how it works.

### ISSUE THREAD

**Issue by SkylerPIlot** [ransty/role-randomizer-ba#4]
As useful as the explanation in Casual Ba disc is. It makes sense to also have it in the readme here. At least basic usage/example format of commands.

**Comment by telescopium73** [comment]
looks like the 'ba-random-command' branch has a readme explaining how to use the plugin

**Comment by SkylerPIlot** [comment]
Ah ok nvm, that readme commit could be rebased and merged into master separately. I would recommend that since if someone wanted to use it and didn't click around they'd be a bit lost. 

Other than that I see no reason to keep this open.

**Comment by telescopium73** [comment]
I think the readme needs to be updated with the ::prefs command and a bit more on usage just like cba disc.
