### ISSUE TITLE
Add option to set prefs for an individual player

### ISSUE THREAD

**Issue by equirs** [ransty/role-randomizer-ba#8]
It can be cumbersome to re-type the entire rando if a mistake was made or if someone changes prefs. Giving the prefs command some optional arguments could be useful, e.g., if I type `::prefs player1 h/c/d` when player1 was previously fill, then it's simple to run a `::rr` that should run with those new roles instead of having to type roles for the whole team again.

**Comment by ransty** [comment]
Yeah I think this is a good idea, I recently had issue with this when a new player joined the team. had to rewrite the whole command.

**Comment by ransty** [comment]
This is basically done in the UI now. The command line code will stay but I don't think many will actually use it.
